### ISSUE TITLE
Tries to install plexpass while issuing non-plexpass instruction

### ISSUE THREAD

**Issue by FastGoNet** [mstinaff/PMS_Updater#45]
Everything seemed to be going according to the instructions, but ended with a failure while instead referencing the plexpass version on a non-plexpass server. Refer to the copied terminal session. 
![image](https://user-images.githubusercontent.com/53932444/62761488-a3798e00-ba3b-11e9-8cf3-86b4dd051c5b.png)

**Comment by FastGoNet** [comment]
These were the instructions I was following: https://www.crackedconsole.com/2019/03/23/manually-updating-plex-on-freenas-including-plexpass-versions/

**Comment by Techassi** [comment]
It is the same for me. I followed the instructions @FastGoNet mentioned above. To get the desired non PlexPass version you need to provide the `-n` parameter to the script: `./PMS_Updater.sh -v -a -n`

**But:** It seems like `https://plex.tv/api/downloads/5.json` and `https://plex.tv/api/downloads/5.json?channel=plexpass` return the same version and download url. So there is no difference between PlexPass and the normal version resulting in an error if you don't use the PlexPass.

I don't actually know how to fix this problem, maybe you need to provide an different path parameter instead of `?channel=plexpass`. Maybe @mstinaff got more insight on this...

**Comment by jbeez** [comment]
I think occasionally the versions are the same exact. I've seen this in the past.
